### ISSUE TITLE
Setup instructions for RPi

### ISSUE THREAD

**Issue by gshafer** [bklavet/Alexa-yun-pi-garagedoor#1]
The website link you have to setup the bridge software on the RPi is broken. Do you have any notes on how to do this?

**Comment by bklavet** [comment]
hey there,  this was awhile back, I don't think I do... but check this out.... does the same thing but you can save the Rpi for something else, you will only need a yun and an echo.

https://github.com/bklavet/Alexa-ArduinoYun-garagedoor-skill

I will update the readme file thanks
